<li class='col-3-1 not-animated' data-animate='fadeInUp'>
                      <div class="portfolio-img"><a  href="[field:arcurl/]" title="Take It Slow"><img src="[field:litpic/]" alt="Take It Slow" /><span class="opacity-overlay"></span><i class="icon-video"></i></a></div>
                      <div class="portfolio-title">
                        <h2><a href="[field:arcurl/]"  title="Take It Slow">[field:title/]</a></h2>
                      </div>
                    </li>