<dl class='list-none metlist'>
          <dt><a href='[field:arcurl/]' title='[field:title/]' target='_self'>[field:title/]</a></dt>
          <dd class='list '>
            <div class='mis'><span>发布日期：[field:pubdate function='strftime("%Y-%m-%d",@me)'/]</span></div>
            <div class='editor met_editor'>
             
              
              <div>[field:description function='cn_substr(@me,150)'/]...</div>
              </span></div>
            <div class='dtail'><span><a href='/a/job/yingpin/' title='在线应聘' target='_self'>在线应聘</a></span><span><a href='[field:arcurl/]' title='查看详细' target='_self'>查看详细</a></span></div>
        </dl>