<?php
$z[0]=Array("field","",4,37);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",67,95);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",115,144);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\n                <li class=\"\"><a class=\"\" href=\"[field:typelink/]\" target=\"\"><strong>[field:typename/]</strong></a></li>\n                ",209,399);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>