<?php
$z[0]=Array("field","",62,81);
$z[0][4]['name']="title";
$z[1]=Array("global","",82,108);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",148,177);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",216,274);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",791,826);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","[field:typename /]",1606,1658);
$z[5][4]['typeid']="1";
$z[6]=Array("channelartlist","\n        <dl class=\"list-none navnow\">\n          <dt id='part2_25' {dede:field name='currentstyle'/}><a href='{dede:field name='typeurl'/}' class=\"zm\"><span>{dede:field name='typename'/}</span></a></dt>\n        </dl>\n        ",1699,2002);
$z[6][4]['type']="son";
$z[6][4]['noself']="yes";
$z[6][4]['typeid']="1";
$z[7]=Array("field","",2207,2229);
$z[7][4]['name']="typename";
$z[8]=Array("field","",2270,2292);
$z[8][4]['name']="position";
$z[9]=Array("field","",2396,2417);
$z[9][4]['name']="content";
$z[10]=Array("include","",2532,2567);
$z[10][4]['filename']="foot.htm";

?>