<?php
$z[0]=Array("field","",62,81);
$z[0][4]['name']="title";
$z[1]=Array("global","",82,108);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",148,177);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",216,274);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",791,826);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1564,1586);
$z[5][4]['name']="position";
$z[6]=Array("type","[field:typename /]",1676,1729);
$z[6][4]['typeid']="15";
$z[7]=Array("channelartlist","\n        <dl class=\"list-none navnow\">\n          <dt id='part2_25' {dede:field name='currentstyle'/}><a href='{dede:field name='typeurl'/}' class=\"zm\"><span>{dede:field name='typename'/}</span></a></dt>\n        </dl>\n        ",1778,2082);
$z[7][4]['type']="son";
$z[7][4]['noself']="yes";
$z[7][4]['typeid']="15";
$z[8]=Array("field","",2312,2331);
$z[8][4]['name']="title";
$z[9]=Array("field","",2447,2465);
$z[9][4]['name']="body";
$z[10]=Array("type","<a href=\"[field:typelink /]\" target='_self' title=\"在线应聘\" class=\"button orange\">在线应聘</a>",2550,2688);
$z[10][4]['typeid']="16";
$z[11]=Array("prenext","",3354,3379);
$z[11][4]['get']="pre";
$z[12]=Array("prenext","",3423,3449);
$z[12][4]['get']="next";
$z[13]=Array("include","",3566,3601);
$z[13][4]['filename']="foot.htm";

?>