<?php
$z[0]=Array("field","",62,81);
$z[0][4]['name']="title";
$z[1]=Array("global","",82,108);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",148,177);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",216,274);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",792,827);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1587,1609);
$z[5][4]['name']="position";
$z[6]=Array("field","",1777,1799);
$z[6][4]['name']="typename";
$z[7]=Array("productimagelist"," \n                <li><a href=\"[field:imgsrc/]\"><img src=\"[field:imgsrc/]\" title=\"[field:text/]\" width=\"150\" height=\"79\" /></a></li>\n                ",2291,2487);
$z[8]=Array("prenext","",3431,3456);
$z[8][4]['get']="pre";
$z[9]=Array("prenext","",3500,3526);
$z[9][4]['get']="next";
$z[10]=Array("include","",3643,3678);
$z[10][4]['filename']="foot.htm";

?>