<?php
$z[0]=Array("field","",370,389);
$z[0][4]['name']="title";
$z[1]=Array("global","",390,416);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",456,478);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",517,568);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3234,3269);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",3788,3810);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\n            <li class=\"\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\n            ",5796,6004);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li class='current'><a href='~typelink~'>~typename~</a></li>";
$z[7]=Array("field","",6550,6569);
$z[7][4]['name']="title";
$z[8]=Array("type","[field:typelink /]",6693,6751);
$z[8][4]['typeid']="0";
$z[8][4]['row']="1";
$z[9]=Array("field","",6753,6775);
$z[9][4]['name']="typename";
$z[10]=Array("field","",6832,6889);
$z[10][4]['name']="pubdate";
$z[10][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[11]=Array("field","",7128,7146);
$z[11][4]['name']="body";
$z[12]=Array("type","[field:typelink /]",7336,7394);
$z[12][4]['typeid']="0";
$z[12][4]['row']="1";
$z[13]=Array("include","",8711,8746);
$z[13][4]['filename']="foot.htm";

?>