<?php
$z[0]=Array("field","",62,81);
$z[0][4]['name']="title";
$z[1]=Array("global","",82,108);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",148,177);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",216,274);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",790,825);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1585,1607);
$z[5][4]['name']="position";
$z[6]=Array("productimagelist"," \n                  <figure> <a href=\"[field:imgsrc/]\"> <img src=\"[field:imgsrc/]\" alt=\"\" width=\"400\" height=\"300\" /> </a>\n                    <figcaption></figcaption>\n                  </figure>\n                  ",1979,2241);
$z[7]=Array("productimagelist"," \n                <li><img src=\"[field:imgsrc/]\" alt=\"\" width=\"70\" height=\"70\" /></li>\n               ",2357,2506);
$z[8]=Array("field","",2680,2699);
$z[8][4]['name']="title";
$z[9]=Array("field","",2763,2780);
$z[9][4]['name']="axh";
$z[10]=Array("field","",2825,2842);
$z[10][4]['name']="app";
$z[11]=Array("field","",2887,2904);
$z[11][4]['name']="ajg";
$z[12]=Array("field","",3217,3235);
$z[12][4]['name']="body";
$z[13]=Array("prenext","",3969,3994);
$z[13][4]['get']="pre";
$z[14]=Array("prenext","",4038,4064);
$z[14][4]['get']="next";
$z[15]=Array("likeart","\n          <li> <a href=\"[field:arcurl/]\" title=\"[field:title /]\" target='_self'> <img src=\"[field:litpic/]\" width =\"213\" height=\"160\" />\n            <h2>[field:title /]</h2>\n            </a> </li>\n            ",4202,4463);
$z[15][4]['row']="2";
$z[15][4]['titlelen']="36";
$z[16]=Array("include","",4558,4593);
$z[16][4]['filename']="foot.htm";

?>