<?php
$z[0]=Array("field","",370,389);
$z[0][4]['name']="title";
$z[1]=Array("global","",390,416);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",456,485);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",524,582);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3347,3382);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",3879,3901);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\n            <li class=\"\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\n            ",5861,6069);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li class='current'><a href='~typelink~'>~typename~</a></li>";
$z[7]=Array("field","",6672,6693);
$z[7][4]['name']="content";
$z[8]=Array("include","",6831,6866);
$z[8][4]['filename']="foot.htm";
$z[9]=Array("global","",8012,8033);
$z[9][4]['name']="cfg_jd";
$z[10]=Array("global","",8034,8055);
$z[10][4]['name']="cfg_wd";
$z[11]=Array("global","",8791,8812);
$z[11][4]['name']="cfg_mc";
$z[12]=Array("global","",8823,8844);
$z[12][4]['name']="cfg_dz";
$z[13]=Array("global","",8853,8874);
$z[13][4]['name']="cfg_jd";
$z[14]=Array("global","",8875,8896);
$z[14][4]['name']="cfg_wd";

?>