<?php
$z[0]=Array("field","",370,389);
$z[0][4]['name']="title";
$z[1]=Array("global","",390,416);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",456,485);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",524,582);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3246,3281);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",3778,3800);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\n            <li class=\"\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\n            ",5760,5968);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li class='current'><a href='~typelink~'>~typename~</a></li>";
$z[7]=Array("field","",6433,6454);
$z[7][4]['name']="content";
$z[8]=Array("include","",6592,6627);
$z[8][4]['filename']="foot.htm";

?>