<?php
$z[0]=Array("field","",369,388);
$z[0][4]['name']="title";
$z[1]=Array("global","",389,415);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",455,484);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",523,581);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3245,3280);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",3777,3799);
$z[5][4]['name']="typename";
$z[6]=Array("list","\n                    <li class='col-3-1 not-animated' data-animate='fadeInUp'>\n                      <div class=\"product-item\">\n                        <div class=\"portfolio-img\"><a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/></a></div>\n                        <div class=\"portfolio-title\">\n                          <h2><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></h2>\n                        </div>\n                      </div>\n                    </li>\n                    ",6127,6714);
$z[6][4]['pagesize']="9";
$z[6][4]['titlelen']="36";
$z[7]=Array("pagelist","",6854,6920);
$z[7][4]['listitem']="index,end,pre,next,pageno";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",7080,7115);
$z[8][4]['filename']="foot.htm";

?>