<?php
$z[0]=Array("field","",62,81);
$z[0][4]['name']="title";
$z[1]=Array("global","",82,108);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",148,177);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",216,274);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",790,825);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1674,1696);
$z[5][4]['name']="typename";
$z[6]=Array("field","",1737,1759);
$z[6][4]['name']="position";
$z[7]=Array("list","\n          <li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\" target='_self'> <img src=\"[field:litpic/]\" width =\"200\" height=\"150\" />\n            <h2>[field:title/]</h2>\n            </a> </li>\n          ",1898,2155);
$z[7][4]['pagesize']="20";
$z[7][4]['titlelen']="36";
$z[8]=Array("pagelist","",2236,2302);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2390,2425);
$z[9][4]['filename']="foot.htm";

?>